
name: build

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Install deps
      run: sudo apt-get install cmake libyaml-cpp-dev libspdlog-dev libclang-cpp11-dev libclang-dev
    - name: Build and unit test
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug ..
        make -j
        make test
