name: build

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install deps
      run: sudo apt install ccache cmake libyaml-cpp-dev libfmt-dev libspdlog-dev clang-12 libclang-12-dev libclang-cpp12-dev
    - name: Build and unit test
      run: |
        make debug
        make test
