name: build

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Update package database
      run: sudo apt -y update
    - name: Install deps
      run: sudo apt -y install git make gcc-10 g++-10 ccache cmake libyaml-cpp-dev libfmt-dev libspdlog-dev clang-12 libclang-12-dev libclang-cpp12-dev
    - name: Select g++ version
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 10
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 10
    - name: Build and unit test
      run: |
        NUMPROC=2 make debug
        make test
